name: Deploy kdoc reference on GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'lse-reference/**'
      - 'komomo-reference/**'
      - 'gradle/**'
      - 'build.gradle.kts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :dokkaGenerate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
